name: Docker backend

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - development
    paths:
      - 'backend/**'
      - '.github/workflows/docker-backend.yml'
      - '.github/workflows/docker-publish.yml'
  pull_request:
    branches:
      - master
      - development
    paths:
      - 'backend/**'
      - '.github/workflows/docker-backend.yml'
      - '.github/workflows/docker-publish.yml'

permissions:
  contents: read

jobs:
  publish:
    uses: ./.github/workflows/docker-publish.yml
    with:
      image: nowtask-app-backend
      context: ./backend
    secrets: inherit
